server:
    error:
        whitelabel:
            enabled: false

spring:
    datasource:
        url: "jdbc:mysql://<IP_ADDRESS>:3306/<DB_NAME>"
        username: "<USER>" # edit
        password: "<PASSWORD>" # edit
    jpa:
        show-sql: true
        database-platform: "org.hibernate.dialect.MySQL8Dialect"
        hibernate:
            ddl-auto: create

app:
    secret: "<generate a 256 length string here>"

